name: File Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  file_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@main
        with:
          token: ${{ secrets.ACTIONS }}
          persist-credentials: false
      - name: File Sync
        uses: kbrashears5/github-action-file-sync@v3.0.0
        with:
          REPOSITORIES: |
            Visual-Analytics-Toolbox/test_repo@unique_like_a_snowflake
          FILES: |
            README.md
          TOKEN: ${{ secrets.ACTIONS }}
          GIT_EMAIL: "stella.a.schlotter@gmail.com"
          GIT_USERNAME: "Stella"
          PULL_REQUEST_BRANCH_NAME: "main"





